url: http://iot-foundations.github.io
baseurl:

# Site settings
title: IoT Foundations
email: carlos@iot/iot-foundations.org
description: Explorando el mundo IoT. Desde el Manifiesto a los detalles más técnicos para entender y desarrollar esta tecnología

# Team names, titles and social links
people:

  - name: Carlos Orts (McOrts)
    social:
      - title: twitter
        url: https://twitter.com/mcorts
      - title: github
        url: https://github.com/mcorts

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  - content

# Menu
menu:
  - projects
  - tutorials
  - workshops
  - talks
  - team
  - contribute
